service: my-lambda-function
provider:
  name: aws
  runtime: nodejs18.x
functions:
  api:
    handler: src/index.api
    events:
      - http:
          path: /
          method: any
          cors: true

plugins:
  - serverless-offline
